[project]
name = "fastapi-scaffold"
version = "0.1.0"
description = "Fastapi scaffold"
readme = "README.md"
authors = [
    { name = "Alex Huaracha", email = "129701149+Alex-Huaracha@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
]

# [project.scripts]
# fastapi-scaffold = "fastapi_scaffold:main"