services:
  - type: web
    plan: free
    name: fastapi-scaffold
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false